// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BIConnector b i connector
// swagger:model BIConnector
type BIConnector struct {

	// enabled
	Enabled *bool `json:"enabled,omitempty"`

	// read preference
	ReadPreference BIConnectorReadPreference `json:"readPreference,omitempty"`
}

// Validate validates this b i connector
func (m *BIConnector) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReadPreference(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BIConnector) validateReadPreference(formats strfmt.Registry) error {

	if swag.IsZero(m.ReadPreference) { // not required
		return nil
	}

	if err := m.ReadPreference.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("readPreference")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BIConnector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BIConnector) UnmarshalBinary(b []byte) error {
	var res BIConnector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
