// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// BIConnectorReadPreference b i connector read preference
// swagger:model BIConnectorReadPreference
type BIConnectorReadPreference string

const (
	// BIConnectorReadPreferencePrimary captures enum value "primary"
	BIConnectorReadPreferencePrimary BIConnectorReadPreference = "primary"
	// BIConnectorReadPreferenceSecondary captures enum value "secondary"
	BIConnectorReadPreferenceSecondary BIConnectorReadPreference = "secondary"
	// BIConnectorReadPreferenceAnalytics captures enum value "analytics"
	BIConnectorReadPreferenceAnalytics BIConnectorReadPreference = "analytics"
)

// for schema
var bIConnectorReadPreferenceEnum []interface{}

func init() {
	var res []BIConnectorReadPreference
	if err := json.Unmarshal([]byte(`["primary","secondary","analytics"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bIConnectorReadPreferenceEnum = append(bIConnectorReadPreferenceEnum, v)
	}
}

func (m BIConnectorReadPreference) validateBIConnectorReadPreferenceEnum(path, location string, value BIConnectorReadPreference) error {
	if err := validate.Enum(path, location, value, bIConnectorReadPreferenceEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this b i connector read preference
func (m BIConnectorReadPreference) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateBIConnectorReadPreferenceEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
