// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ClusterType cluster type
// swagger:model ClusterType
type ClusterType string

const (
	// ClusterTypeREPLICASET captures enum value "REPLICASET"
	ClusterTypeREPLICASET ClusterType = "REPLICASET"
	// ClusterTypeSHARDED captures enum value "SHARDED"
	ClusterTypeSHARDED ClusterType = "SHARDED"
	// ClusterTypeGEOSHARDED captures enum value "GEOSHARDED"
	ClusterTypeGEOSHARDED ClusterType = "GEOSHARDED"
)

// for schema
var clusterTypeEnum []interface{}

func init() {
	var res []ClusterType
	if err := json.Unmarshal([]byte(`["REPLICASET","SHARDED","GEOSHARDED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clusterTypeEnum = append(clusterTypeEnum, v)
	}
}

func (m ClusterType) validateClusterTypeEnum(path, location string, value ClusterType) error {
	if err := validate.Enum(path, location, value, clusterTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this cluster type
func (m ClusterType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateClusterTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
