// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Conflict conflict
// swagger:model Conflict
type Conflict struct {

	// error code
	ErrorCode int64 `json:"error,omitempty"`

	// message
	Message string `json:"detail,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// unused
	Unused string `json:"message,omitempty"`
}

// Validate validates this conflict
func (m *Conflict) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Conflict) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Conflict) UnmarshalBinary(b []byte) error {
	var res Conflict
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
