// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RestoreJobResponseDelivery restore job response delivery
// swagger:model RestoreJobResponseDelivery
type RestoreJobResponseDelivery struct {

	// method name
	MethodName string `json:"methodName,omitempty"`

	// Current status of the downloadable file.
	StatusName string `json:"statusName,omitempty"`
}

// Validate validates this restore job response delivery
func (m *RestoreJobResponseDelivery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethodName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStatusName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var restoreJobResponseDeliveryTypeMethodNamePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AUTOMATED_RESTORE","HTTP"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		restoreJobResponseDeliveryTypeMethodNamePropEnum = append(restoreJobResponseDeliveryTypeMethodNamePropEnum, v)
	}
}

const (
	// RestoreJobResponseDeliveryMethodNameAUTOMATEDRESTORE captures enum value "AUTOMATED_RESTORE"
	RestoreJobResponseDeliveryMethodNameAUTOMATEDRESTORE string = "AUTOMATED_RESTORE"
	// RestoreJobResponseDeliveryMethodNameHTTP captures enum value "HTTP"
	RestoreJobResponseDeliveryMethodNameHTTP string = "HTTP"
)

// prop value enum
func (m *RestoreJobResponseDelivery) validateMethodNameEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, restoreJobResponseDeliveryTypeMethodNamePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RestoreJobResponseDelivery) validateMethodName(formats strfmt.Registry) error {

	if swag.IsZero(m.MethodName) { // not required
		return nil
	}

	// value enum
	if err := m.validateMethodNameEnum("methodName", "body", m.MethodName); err != nil {
		return err
	}

	return nil
}

var restoreJobResponseDeliveryTypeStatusNamePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NOT_STARTED","IN_PROGRESS","READY","FAILED","INTERRUPTED","EXPIRED","MAX_DOWNLOADS_EXCEEDED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		restoreJobResponseDeliveryTypeStatusNamePropEnum = append(restoreJobResponseDeliveryTypeStatusNamePropEnum, v)
	}
}

const (
	// RestoreJobResponseDeliveryStatusNameNOTSTARTED captures enum value "NOT_STARTED"
	RestoreJobResponseDeliveryStatusNameNOTSTARTED string = "NOT_STARTED"
	// RestoreJobResponseDeliveryStatusNameINPROGRESS captures enum value "IN_PROGRESS"
	RestoreJobResponseDeliveryStatusNameINPROGRESS string = "IN_PROGRESS"
	// RestoreJobResponseDeliveryStatusNameREADY captures enum value "READY"
	RestoreJobResponseDeliveryStatusNameREADY string = "READY"
	// RestoreJobResponseDeliveryStatusNameFAILED captures enum value "FAILED"
	RestoreJobResponseDeliveryStatusNameFAILED string = "FAILED"
	// RestoreJobResponseDeliveryStatusNameINTERRUPTED captures enum value "INTERRUPTED"
	RestoreJobResponseDeliveryStatusNameINTERRUPTED string = "INTERRUPTED"
	// RestoreJobResponseDeliveryStatusNameEXPIRED captures enum value "EXPIRED"
	RestoreJobResponseDeliveryStatusNameEXPIRED string = "EXPIRED"
	// RestoreJobResponseDeliveryStatusNameMAXDOWNLOADSEXCEEDED captures enum value "MAX_DOWNLOADS_EXCEEDED"
	RestoreJobResponseDeliveryStatusNameMAXDOWNLOADSEXCEEDED string = "MAX_DOWNLOADS_EXCEEDED"
)

// prop value enum
func (m *RestoreJobResponseDelivery) validateStatusNameEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, restoreJobResponseDeliveryTypeStatusNamePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RestoreJobResponseDelivery) validateStatusName(formats strfmt.Registry) error {

	if swag.IsZero(m.StatusName) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusNameEnum("statusName", "body", m.StatusName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RestoreJobResponseDelivery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestoreJobResponseDelivery) UnmarshalBinary(b []byte) error {
	var res RestoreJobResponseDelivery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
