// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RestoreJobDelivery restore job delivery
// swagger:model RestoreJobDelivery
type RestoreJobDelivery struct {

	// method name
	MethodName string `json:"methodName,omitempty"`

	// target cluster name
	TargetClusterName string `json:"targetClusterName,omitempty"`

	// target group Id
	TargetGroupID string `json:"targetGroupId,omitempty"`
}

// Validate validates this restore job delivery
func (m *RestoreJobDelivery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethodName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var restoreJobDeliveryTypeMethodNamePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AUTOMATED_RESTORE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		restoreJobDeliveryTypeMethodNamePropEnum = append(restoreJobDeliveryTypeMethodNamePropEnum, v)
	}
}

const (
	// RestoreJobDeliveryMethodNameAUTOMATEDRESTORE captures enum value "AUTOMATED_RESTORE"
	RestoreJobDeliveryMethodNameAUTOMATEDRESTORE string = "AUTOMATED_RESTORE"
)

// prop value enum
func (m *RestoreJobDelivery) validateMethodNameEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, restoreJobDeliveryTypeMethodNamePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RestoreJobDelivery) validateMethodName(formats strfmt.Registry) error {

	if swag.IsZero(m.MethodName) { // not required
		return nil
	}

	// value enum
	if err := m.validateMethodNameEnum("methodName", "body", m.MethodName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RestoreJobDelivery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestoreJobDelivery) UnmarshalBinary(b []byte) error {
	var res RestoreJobDelivery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
