// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SnapshotSchedule snapshot schedule
// swagger:model SnapshotSchedule
type SnapshotSchedule struct {

	// cluster checkpoint interval min
	ClusterCheckpointIntervalMin int64 `json:"clusterCheckpointIntervalMin,omitempty"`

	// cluster Id
	ClusterID string `json:"clusterId,omitempty"`

	// daily snapshot retention days
	DailySnapshotRetentionDays int64 `json:"dailySnapshotRetentionDays,omitempty"`

	// group Id
	GroupID string `json:"groupId,omitempty"`

	// links
	Links []*Link `json:"links"`

	// monthly snapshot retention months
	MonthlySnapshotRetentionMonths int64 `json:"monthlySnapshotRetentionMonths,omitempty"`

	// point in time window hours
	PointInTimeWindowHours int64 `json:"pointInTimeWindowHours,omitempty"`

	// snapshot interval hours
	SnapshotIntervalHours int64 `json:"snapshotIntervalHours,omitempty"`

	// snapshot retention days
	SnapshotRetentionDays int64 `json:"snapshotRetentionDays,omitempty"`

	// weekly snapshot retention weeks
	WeeklySnapshotRetentionWeeks int64 `json:"weeklySnapshotRetentionWeeks,omitempty"`
}

// Validate validates this snapshot schedule
func (m *SnapshotSchedule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotSchedule) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	for i := 0; i < len(m.Links); i++ {

		if swag.IsZero(m.Links[i]) { // not required
			continue
		}

		if m.Links[i] != nil {

			if err := m.Links[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("links" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SnapshotSchedule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnapshotSchedule) UnmarshalBinary(b []byte) error {
	var res SnapshotSchedule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
