// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SnapshotTimestamp snapshot timestamp
// swagger:model SnapshotTimestamp
type SnapshotTimestamp struct {

	// Timestamp in ISO 8601 date and time format in UTC of the latest oplog entry in the snapshot.
	Date string `json:"date,omitempty"`

	// Order of all operations completed at the latest oplog entry in the snapshot.
	Increment float64 `json:"increment,omitempty"`
}

// Validate validates this snapshot timestamp
func (m *SnapshotTimestamp) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SnapshotTimestamp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnapshotTimestamp) UnmarshalBinary(b []byte) error {
	var res SnapshotTimestamp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
