// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UpdatePeerRequest update peer request
// swagger:model UpdatePeerRequest
type UpdatePeerRequest struct {

	// aws account Id
	AwsAccountID string `json:"awsAccountId,omitempty"`

	// provider name
	ProviderName string `json:"providerName,omitempty"`

	// route table cidr block
	RouteTableCidrBlock string `json:"routeTableCidrBlock,omitempty"`

	// vpc Id
	VpcID string `json:"vpcId,omitempty"`
}

// Validate validates this update peer request
func (m *UpdatePeerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UpdatePeerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdatePeerRequest) UnmarshalBinary(b []byte) error {
	var res UpdatePeerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
